format = """
$battery\
$username\
$hostname\
$sudo\
$directory\
$git_branch\
$git_status\
$git_metrics\
$lua\
$nodejs\
$ruby\
$python\
$rust\
$os\
$character
"""

[username]
style_user = 'yellow bold'
style_root = 'red bold'
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
style = 'blue bold'
format = '@[$hostname$ssh_symbol]($style)'

[sudo]
disabled = false
format = " [as $symbol]($style)"

[directory]
format = ' via [$path]($style)[$read_only]($read_only_style) '
truncation_symbol = "../"

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
format = "[$symbol]($style) "

[[battery.display]]
threshold = 100


[git_metrics]
disabled = false

[os]
disabled = false

[character]
format = "\n$symbol "

